WITH MAX_ALGORITHM_TYPE AS (
    SELECT ALGORITHM_TYPE, COUNT(ID) 'COUNT'
    FROM PROBLEMS
    GROUP BY ALGORITHM_TYPE
)

SELECT ALGORITHM_TYPE
FROM MAX_ALGORITHM_TYPE
ORDER BY COUNT DESC, ALGORITHM_TYPE ASC
LIMIT 1;