# 처음 푼 쿼리
# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O LEFT OUTER JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL
# ORDER BY O.ANIMAL_ID
# 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없어야 함
# 따라서, 입양 기록에 보호소에 들어온 기록을 LEFT JOIN하여
# 입양 기록 ID는 존재하나 보호소 기록 ID는 NULL인 데이터를 찾으면 됨
# ANIMAL_ID가 왜래 키이므로 ANIMAL_ID 컬럼이 같다는 조건을 사용해야 함

# 다시 푼 쿼리
# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I USING(ANIMAL_ID)
# WHERE O.DATETIME IS NOT NULL AND I.DATETIME IS NULL
# ORDER BY O.ANIMAL_ID

# 다시 푼 쿼리(1) - LEFT JOIN을 통해
# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I USING(ANIMAL_ID)
# WHERE I.DATETIME IS NULL AND O.DATETIME IS NOT NULL
# ORDER BY O.ANIMAL_ID

# 다시 푼 쿼리(2) - WHERE 절 서브쿼리를 통해
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                        FROM ANIMAL_INS)
ORDER BY ANIMAL_ID