# WITH를 이용하지 않은 풀이
-- SELECT A.ID ID, COUNT(B.ID) CHILD_COUNT # A.ID로 GROUP BY 했을 때, B.ID의 값이 없다면(NULL) 0으로 집계됨
-- FROM ECOLI_DATA A
-- LEFT JOIN ECOLI_DATA B
-- ON A.ID = B.PARENT_ID
-- GROUP BY A.ID
-- ORDER BY A.ID;

# WITH를 이용한 풀이
WITH CTE AS (
    SELECT PARENT_ID, COUNT(ID) CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)

SELECT E.ID, IFNULL(C.CHILD_COUNT, 0) CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN CTE C
ON E.ID = C.PARENT_ID
ORDER BY E.ID;