# SUBQUERY를 이용한 풀이
# 두 개의 컬럼 값을 조합하여 IN 절에서 사용하려면 반드시 괄호로 묶기
-- SELECT I.ID, N.FISH_NAME, I.LENGTH
-- FROM FISH_INFO I JOIN FISH_NAME_INFO N
-- ON I.FISH_TYPE = N.FISH_TYPE
-- WHERE (I.FISH_TYPE, I.LENGTH) IN (
--     SELECT FISH_TYPE, MAX(LENGTH)
--     FROM FISH_INFO
--     GROUP BY FISH_TYPE
--     )
-- ORDER BY I.ID

# USING을 이용한 풀이
# 두 테이블의 공통 컬럼 이름이 'FISH_TYPE'로 동일하므로, USING을 이용해 간소화
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N
USING(FISH_TYPE)
WHERE (I.FISH_TYPE, I.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    )
ORDER BY I.ID