# WITH를 이용한 풀이
-- WITH DEPT_SAL AS(
--     SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
--     FROM HR_EMPLOYEES
--     GROUP BY DEPT_ID
--     )
--     
-- SELECT DEPT_ID, DEPT_NAME_EN, AVG_SAL
-- FROM HR_DEPARTMENT D JOIN DEPT_SAL S USING (DEPT_ID)
-- ORDER BY AVG_SAL DESC

# JOIN을 이용한 풀이
# 데이터 일관성에 의해 DEPT_ID로만 GROUP BY를 해도 동일한 결과가 출력되나,
# 명확하고 쉬운 유지보수를 위해 SELECT 절에 나오는 모든 열에 대해 GROUP BY를 진행함
SELECT DEPT_ID, DEPT_NAME_EN, ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_DEPARTMENT D JOIN HR_EMPLOYEES E USING (DEPT_ID)
GROUP BY DEPT_ID, DEPT_NAME_EN
ORDER BY AVG_SAL DESC
