# JOIN을 이용한 풀이
# 입양을 간 기록은 있으나, 보호소에 들어온 기록이 없는 동물은
# 'O'와 'I' 테이블을 LEFT JOIN 했을 때, DATETIME을 비롯해 ANUMAL_TYPE, NAME 등 모든 컬럼이 NULL이므로, 다른 조건을 이용해도 됨
# 예) WHERE I.ANIMAL_TYPE IS NULL AND O.DATETIME IS NOT NULL
-- SELECT O.ANIMAL_ID, O.NAME
-- FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I USING(ANIMAL_ID)
-- WHERE I.DATETIME IS NULL AND O.DATETIME IS NOT NULL
-- ORDER BY O.ANIMAL_ID

# SUBQUERY를 이용한 풀이
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    )
ORDER BY ANIMAL_ID