# WITH와 JOIN을 이용한 풀이
-- WITH MAX_VIEWS_USED_GOODS AS(
--     SELECT BOARD_ID
--     FROM USED_GOODS_BOARD
--     WHERE VIEWS = (
--         SELECT MAX(VIEWS)
--         FROM USED_GOODS_BOARD
--         )
--     )

-- SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
-- FROM MAX_VIEWS_USED_GOODS JOIN USED_GOODS_FILE USING(BOARD_ID)
-- ORDER BY FILE_ID DESC

# WHERE 절 SUBQUERY만을 이용한 풀이
# 출력하려는 결과가 모두 USED_GOODS_FILE 테이블에 포함되어 있기 때문에 가능함
SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
    )
ORDER BY FILE_ID DESC