# SUBQUERY에서 IN 연산자는 다중 컬럼에 대해 사용할 수 있음
# 예를 들어, (컬럼1, 컬럼2) IN (특정 값1, 특정 값2)와 같이 다중 컬럼 조합을 찾을 수 있음
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES 
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;