# COALESCE를 이용한 풀이
# COALESCE는 여러 인자를 받아 첫 번째 NULL이 아닌 값을 반환
# 거의 모든 주요 DBMS에서 지원
-- SELECT COUNT(ID) AS FISH_COUNT, MAX(COALESCE(LENGTH, 10)) AS MAX_LENGTH, FISH_TYPE
-- FROM FISH_INFO
-- GROUP BY FISH_TYPE
-- HAVING AVG(COALESCE(LENGTH, 10)) >= 33
-- ORDER BY FISH_TYPE

# IFNULL을 이용한 풀이
# IFNULL은 두 개의 인자를 받아 첫 번째 인자가 NULL이면 두 번째 인자를 반환
# MySQL에서만 사용 가능
SELECT COUNT(ID) AS FISH_COUNT, MAX(IFNULL(LENGTH, 10)) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE