SELECT 
    PRODUCT_ID,
    PRODUCT_NAME,
    SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM 
    FOOD_ORDER O
JOIN 
    FOOD_PRODUCT P 
    USING (PRODUCT_ID)
WHERE 
    DATE_FORMAT(PRODUCE_DATE, '%y%m') = '2205'
GROUP BY 
    PRODUCT_ID,
    PRODUCT_NAME
ORDER BY 
    TOTAL_SALES DESC,
    PRODUCT_ID;