WITH FRONT_END_CODE AS (
    SELECT
        (SELECT SUM(CODE)
         FROM SKILLCODES
         WHERE CATEGORY = 'Front End') AS FECODE
)
SELECT
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM
    DEVELOPERS,
    FRONT_END_CODE
WHERE
    SKILL_CODE & FECODE
ORDER BY
    ID;