SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    REST_REVIEW R
    JOIN MEMBER_PROFILE P USING (MEMBER_ID)
WHERE
    MEMBER_ID IN (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(REVIEW_ID) = (
            SELECT COUNT(REVIEW_ID) AS COUNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT DESC
            LIMIT 1
        )
    )
ORDER BY
    REVIEW_DATE,
    REVIEW_TEXT