# LIKE를 이용한 풀이
-- SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
-- FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE (SEX_UPON_INTAKE LIKE '%Intact%')
-- AND (SEX_UPON_OUTCOME LIKE '%Spayed%' or SEX_UPON_OUTCOME LIKE '%Neutered%')
-- ORDER BY I.ANIMAL_ID

# LIKE를 이용한 풀이 - 간소화
-- SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
-- FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE (SEX_UPON_INTAKE LIKE '%Intact%')
-- AND (SEX_UPON_OUTCOME NOT LIKE '%Intact%')
-- ORDER BY I.ANIMAL_ID

# WHERE 조건을 이용한 풀이
# SEX_UPON_INTAKE, SEX_UPON_OUTCOME의 상태가 중성화 여부 이외에도 다양하다면 적용 불가함
-- SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
-- FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE SEX_UPON_INTAKE != SEX_UPON_OUTCOME
-- ORDER BY I.ANIMAL_ID

# REGEXP를 이용한 풀이
-- SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
-- FROM ANIMAL_INS I JOIN ANIMAL_OUTS O USING(ANIMAL_ID)
-- WHERE I.SEX_UPON_INTAKE REGEXP 'Intact'
-- AND O.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered' 
-- ORDER BY I.ANIMAL_ID

# REGEXP를 이용한 풀이 - 간소화
SELECT ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O USING(ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE '%Intact%' AND SEX_UPON_OUTCOME REGEXP ('Spayed|Neutered')
ORDER BY ANIMAL_ID
