# DEVELOPERS의 SKILL_CODE와 다르게, SKILLCODES의 CODE는 무조건 한 자리의 '1' 비트만을 갖는다.
# 예를 들어, 'C++'의 경우 b'100'을, 'Python'의 경우 b'100000000'을 갖는다.
# (설명 참고: 스킬의 코드는 2진수로 표현했을 때 각 bit로 구분될 수 있도록 2의 제곱수로 구성되어 있습니다.)
# 따라서, SKILLCODES의 CODE는 각각 구분되므로 더해도 문제가 없음.
WITH CODE_LIST AS (
    SELECT
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS FRONT_END_CODE,
        (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python') AS PYTHON_CODE,
        (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'C#') AS CSHARP_CODE
)

SELECT CASE
        WHEN SKILL_CODE & FRONT_END_CODE > 0 AND SKILL_CODE & PYTHON_CODE > 0 THEN 'A'
        WHEN SKILL_CODE & CSHARP_CODE > 0 THEN 'B'
        WHEN SKILL_CODE & FRONT_END_CODE > 0 THEN 'C'
        END AS GRADE, ID, EMAIL
FROM DEVELOPERS, CODE_LIST
WHERE SKILL_CODE & FRONT_END_CODE OR SKILL_CODE & CSHARP_CODE
ORDER BY GRADE, ID;