SELECT HISTORY_ID,
CASE
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN FLOOR(DAILY_FEE * 0.90 * (DATEDIFF(END_DATE, START_DATE) + 1))
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN FLOOR(DAILY_FEE * 0.93 * (DATEDIFF(END_DATE, START_DATE) + 1))
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >=  7 THEN FLOOR(DAILY_FEE * 0.95 * (DATEDIFF(END_DATE, START_DATE) + 1))
    ELSE FLOOR(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)) END FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR C USING(CAR_ID)
WHERE CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;