# LEFT JOIN을 이용한 풀이
-- SELECT E1.NAME AS EMPLOYEE
-- FROM EMPLOYEE E1
-- LEFT JOIN EMPLOYEE E2
-- ON E1.MANAGERID = E2.ID
-- WHERE E1.SALARY > E2.SALARY;

# SUBQUERY를 이용한 풀이
-- SELECT NAME AS EMPLOYEE
-- FROM EMPLOYEE
-- WHERE SALARY > (
--     SELECT SALARY
--     FROM EMPLOYEE AS MANAGER
--     WHERE MANAGER.ID = EMPLOYEE.MANAGERID
-- );

# SELF JOIN을 이용한 풀이
SELECT E1.NAME AS EMPLOYEE
FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.MANAGERID = E2.ID
  AND E1.SALARY > E2.SALARY;