WITH CTE AS (
    SELECT 
        USER_ID, 
        PROBLEM_ID, 
        RANK() OVER(PARTITION BY USER_ID, PROBLEM_ID ORDER BY TIMESTAMP) AS NUMBER,
        CASE
            WHEN SUBMITTED = CORRECT_ANSWER THEN 1
            ELSE 0
            END AS ANSWER
    FROM SUBMISSIONS S
    JOIN PROBLEMS P
    USING (PROBLEM_ID)
)

SELECT 
    NUMBER AS NTH_SUBMISSION,
    ROUND(SUM(ANSWER) / COUNT(*) * 100) AS CORRECT_RATE
FROM CTE
GROUP BY NTH_SUBMISSION;
