# WITH를 이용한 풀이
-- WITH SUBTABLE AS (
--     SELECT 
--         YEAR(DIFFERENTIATION_DATE) AS YEAR, 
--         MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
--     FROM 
--         ECOLI_DATA
--     GROUP BY 
--         YEAR
-- )
-- SELECT 
--     E.YEAR(DIFFERENTIATION_DATE) AS YEAR, 
--     S.MAX_SIZE_OF_COLONY - E.SIZE_OF_COLONY AS YEAR_DEV, 
--     E.ID
-- FROM 
--     ECOLI_DATA E 
-- JOIN 
--     SUBTABLE S 
-- ON 
--     YEAR(E.DIFFERENTIATION_DATE) = S.YEAR 
-- ORDER BY 
--     YEAR, 
--     YEAR_DEV;

SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (
        SELECT MAX(SIZE_OF_COLONY)
        FROM ECOLI_DATA
        WHERE YEAR(DIFFERENTIATION_DATE) = YEAR
    ) - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM 
    ECOLI_DATA 
ORDER BY 
    YEAR, 
    YEAR_DEV;