# '평균' 대여 기간을 대여 기간이 7일 이상인 조건으로 착각하지 않도록 주의(HAVING 조건을 WHERE 조건으로 착각하지 않도록 주의)
# DATEDIFF 함수는 두 날짜 사이의 일수를 반환하므로, '대여 기간'을 구하려면 1을 더해줘야 함
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;