# 첫 번째 풀이
-- SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
-- FROM BOOK AS B, AUTHOR AS A
-- WHERE B.AUTHOR_ID = A.AUTHOR_ID AND CATEGORY = '경제'
-- ORDER BY PUBLISHED_DATE;

# 두 번째 풀이
-- SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
-- FROM BOOK AS B JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
-- WHERE CATEGORY = '경제'
-- ORDER BY PUBLISHED_DATE;

# 세 번째 풀이
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK B JOIN AUTHOR A USING(AUTHOR_ID)
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE;