# OR을 이용한 풀이
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO F JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER'

# IN을 이용한 풀이
# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO F JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
# WHERE FISH_NAME IN ('BASS', 'SNAPPER')
